# Constants for Pizza Calculator
PEOPLE_PER_LARGE = 7
PEOPLE_PER_MEDIUM = 3
PEOPLE_PER_SMALL = 1

# inches
DIAMETER_LARGE = 20
DIAMETER_MEDIUM = 16
DIAMETER_SMALL = 12

# dollars
COST_LARGE = 14.68
COST_MEDIUM = 11.48
COST_SMALL = 7.28
